
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.ActivateAdapter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.ApplyLocation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.CreateLocation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.DeactivateAdapter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.DeleteLocation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.EditLocation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.ExportPresets")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.ExtractConfigToNewLocation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.GetExternalIp")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.ImportPresets")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.ManualSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.IpSwitcher.IpSwitcherViewModel.RefreshDhcpLease")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.WiFiManager.WiFiProfilesViewModel.DeleteSelected")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.WiFiManager.WiFiProfilesViewModel.Export")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Language Usage Opportunities", "RECS0002:Convert anonymous method to method group", Justification = "<Pending>", Scope = "member", Target = "~P:Deucalion.IP_Switcher.Features.WiFiManager.WiFiProfilesViewModel.Import")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0165:Asynchronous methods should return a Task instead of void", Justification = "<Pending>", Scope = "member", Target = "~M:Deucalion.IP_Switcher.Features.WiFiManager.InterfaceModel.UpdateInformation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Vulnerability", "S1104:Fields should not have public accessibility", Justification = "<Pending>", Scope = "type", Target = "~T:NativeWifi.Wlan")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S2346:Flags enumerations zero-value members should be named \"None\"", Justification = "<Pending>", Scope = "type", Target = "~T:NativeWifi.Wlan")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S2344:Enumeration type names should not have \"Flags\" or \"Enum\" suffixes", Justification = "<Pending>", Scope = "type", Target = "~T:NativeWifi.Wlan")]

