//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deucalion.IP_Switcher.Features.WiFiManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WIFINetworksViewLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WIFINetworksViewLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deucalion.IP_Switcher.Features.WiFiManager.Resources.WIFINetworksViewLoc", typeof(WIFINetworksViewLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABLE NETWORKS.
        /// </summary>
        public static string AvailableNetworks {
            get {
                return ResourceManager.GetString("AvailableNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoconf.
        /// </summary>
        public static string Interface_Autoconf {
            get {
                return ResourceManager.GetString("Interface_Autoconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BssType.
        /// </summary>
        public static string Interface_BssType {
            get {
                return ResourceManager.GetString("Interface_BssType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Interface_Channel {
            get {
                return ResourceManager.GetString("Interface_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Interface_Mode {
            get {
                return ResourceManager.GetString("Interface_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Interface_Profile {
            get {
                return ResourceManager.GetString("Interface_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSSI.
        /// </summary>
        public static string Interface_RSSI {
            get {
                return ResourceManager.GetString("Interface_RSSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signalquality.
        /// </summary>
        public static string Interface_SignalQuality {
            get {
                return ResourceManager.GetString("Interface_SignalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Interface_State {
            get {
                return ResourceManager.GetString("Interface_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERFACES.
        /// </summary>
        public static string Interfaces {
            get {
                return ResourceManager.GetString("Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERFACE STATE.
        /// </summary>
        public static string InterfaceState {
            get {
                return ResourceManager.GetString("InterfaceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth. algorithm.
        /// </summary>
        public static string Network_AuthAlgorithm {
            get {
                return ResourceManager.GetString("Network_AuthAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiper algorithm.
        /// </summary>
        public static string Network_ChiperAlgorithm {
            get {
                return ResourceManager.GetString("Network_ChiperAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectable.
        /// </summary>
        public static string Network_Connectable {
            get {
                return ResourceManager.GetString("Network_Connectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .11 BssType.
        /// </summary>
        public static string Network_Dot11BssType {
            get {
                return ResourceManager.GetString("Network_Dot11BssType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .11 SSID.
        /// </summary>
        public static string Network_Dot11SSID {
            get {
                return ResourceManager.GetString("Network_Dot11SSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Network_Flags {
            get {
                return ResourceManager.GetString("Network_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Bssids.
        /// </summary>
        public static string Network_NoBssids {
            get {
                return ResourceManager.GetString("Network_NoBssids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Network_NotConnectableReason {
            get {
                return ResourceManager.GetString("Network_NotConnectableReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Network_SecurityEnabled {
            get {
                return ResourceManager.GetString("Network_SecurityEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signalquality.
        /// </summary>
        public static string Network_SignalQuality {
            get {
                return ResourceManager.GetString("Network_SignalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETWORKINFORMATION.
        /// </summary>
        public static string NetworkInformation {
            get {
                return ResourceManager.GetString("NetworkInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIRELESS NETWORKS.
        /// </summary>
        public static string WirelessNetworks {
            get {
                return ResourceManager.GetString("WirelessNetworks", resourceCulture);
            }
        }
    }
}
