//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deucalion.IP_Switcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainViewLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainViewLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deucalion.IP_Switcher.Resources.MainViewLoc", typeof(MainViewLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivera.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTIVA NÄTVERKSKORT.
        /// </summary>
        public static string ActiveAdaptersHeader {
            get {
                return ResourceManager.GetString("ActiveAdaptersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Använd på valt kort.
        /// </summary>
        public static string ApplyLocation {
            get {
                return ResourceManager.GetString("ApplyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa ny....
        /// </summary>
        public static string CreateLocation {
            get {
                return ResourceManager.GetString("CreateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anycast IP.
        /// </summary>
        public static string Current_AnycastIp {
            get {
                return ResourceManager.GetString("Current_AnycastIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHCP.
        /// </summary>
        public static string Current_DhcpEnabled {
            get {
                return ResourceManager.GetString("Current_DhcpEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHCP servrar.
        /// </summary>
        public static string Current_DhcpServers {
            get {
                return ResourceManager.GetString("Current_DhcpServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS servrar.
        /// </summary>
        public static string Current_DnsServers {
            get {
                return ResourceManager.GetString("Current_DnsServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateways.
        /// </summary>
        public static string Current_Gateways {
            get {
                return ResourceManager.GetString("Current_Gateways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP addresser.
        /// </summary>
        public static string Current_Ip {
            get {
                return ResourceManager.GetString("Current_Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC address.
        /// </summary>
        public static string Current_MacAddress {
            get {
                return ResourceManager.GetString("Current_MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuella inställningar.
        /// </summary>
        public static string Current_ManualSettings {
            get {
                return ResourceManager.GetString("Current_ManualSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicast IP.
        /// </summary>
        public static string Current_MulticastIp {
            get {
                return ResourceManager.GetString("Current_MulticastIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara som ny förinställning.
        /// </summary>
        public static string Current_SaveAsNew {
            get {
                return ResourceManager.GetString("Current_SaveAsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastighet.
        /// </summary>
        public static string Current_Speed {
            get {
                return ResourceManager.GetString("Current_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Current_Status {
            get {
                return ResourceManager.GetString("Current_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINS.
        /// </summary>
        public static string Current_WinsEnabled {
            get {
                return ResourceManager.GetString("Current_WinsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINS servrar.
        /// </summary>
        public static string Current_WinsServers {
            get {
                return ResourceManager.GetString("Current_WinsServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTUELL INSTÄLLNING.
        /// </summary>
        public static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaktivera.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radera.
        /// </summary>
        public static string DeleteLocation {
            get {
                return ResourceManager.GetString("DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera....
        /// </summary>
        public static string EditLocation {
            get {
                return ResourceManager.GetString("EditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern IP.
        /// </summary>
        public static string ExternalIp {
            get {
                return ResourceManager.GetString("ExternalIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INAKTIVA NÄTVERKSKORT.
        /// </summary>
        public static string InactiveAdaptersHeader {
            get {
                return ResourceManager.GetString("InactiveAdaptersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FÖRINSTÄLLNING.
        /// </summary>
        public static string LocationHeader {
            get {
                return ResourceManager.GetString("LocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppdatera.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
