//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deucalion.IP_Switcher.Features.IpSwitcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IpSwitcherViewModelLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IpSwitcherViewModelLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deucalion.IP_Switcher.Features.IpSwitcher.Resources.IpSwitcherViewModelLoc", typeof(IpSwitcherViewModelLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed.
        /// </summary>
        public static string ActivationFailed {
            get {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation failed.
        /// </summary>
        public static string DeactivationFailed {
            get {
                return ResourceManager.GetString("DeactivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read presets from file:{0}{1}{0}{0}Exception:{0}{2}.
        /// </summary>
        public static string ErrorImportingLocations {
            get {
                return ResourceManager.GetString("ErrorImportingLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPSwitcherExport.xml.
        /// </summary>
        public static string ExportDefaultFilename {
            get {
                return ResourceManager.GetString("ExportDefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml files|*.xml.
        /// </summary>
        public static string ExportFilter {
            get {
                return ResourceManager.GetString("ExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New preset.
        /// </summary>
        public static string NewLocationDescription {
            get {
                return ResourceManager.GetString("NewLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search failed.
        /// </summary>
        public static string SearchFailed {
            get {
                return ResourceManager.GetString("SearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating adapter....
        /// </summary>
        public static string Status_ActivatingAdapter {
            get {
                return ResourceManager.GetString("Status_ActivatingAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying setting....
        /// </summary>
        public static string Status_ApplyingLocation {
            get {
                return ResourceManager.GetString("Status_ApplyingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating adapter....
        /// </summary>
        public static string Status_DeactivatingAdapter {
            get {
                return ResourceManager.GetString("Status_DeactivatingAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Status_Idle {
            get {
                return ResourceManager.GetString("Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No status.
        /// </summary>
        public static string Status_None {
            get {
                return ResourceManager.GetString("Status_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating list of adapters....
        /// </summary>
        public static string Status_UpdatingAdapters {
            get {
                return ResourceManager.GetString("Status_UpdatingAdapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from system: {0}.
        /// </summary>
        public static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
    }
}
